###
GET http://localhost/

###
GET http://localhost/api

###
POST http://localhost/api/main
Content-Type: application/json

{}

###
GET http://localhost/api/main

###
GET http://localhost/api/main/1

###
PATCH http://localhost/api/main/1
Content-Type: application/json

{}

###
DELETE http://localhost/api/main/1
